version: '3.8'
services:
  angular-app:
    image: node:14
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "
      npm install -g @angular/cli@latest &&
      npm install &&
      ng serve --host 0.0.0.0"
    ports:
      - '4200:4200'
